/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.Client;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.io.IOException;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.BadLocationException;
import javax.swing.text.html.HTMLDocument;
import javax.swing.text.html.HTMLEditorKit;

/**
 *
 * @author Anh Nguyen
 */
public class Chat extends javax.swing.JFrame {

    /**
     * Creates new form ChatView
     */
    private Map<String, JScrollPane> listOnlineUsers = new HashMap<>();
    private Map<String, JScrollPane> listRooms = new HashMap<>();

    public Chat() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOnlineUsers = new javax.swing.JTable();
        panelChatView = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaSend = new javax.swing.JTextArea();
        btnSend = new javax.swing.JButton();
        lbSendTo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblOnlineUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Online"
            }
        ));
        tblOnlineUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOnlineUsersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblOnlineUsers);

        panelChatView.setBackground(new java.awt.Color(187, 187, 187));
        panelChatView.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelChatView.setToolTipText("");

        javax.swing.GroupLayout panelChatViewLayout = new javax.swing.GroupLayout(panelChatView);
        panelChatView.setLayout(panelChatViewLayout);
        panelChatViewLayout.setHorizontalGroup(
            panelChatViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );
        panelChatViewLayout.setVerticalGroup(
            panelChatViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 263, Short.MAX_VALUE)
        );

        txtAreaSend.setColumns(20);
        txtAreaSend.setRows(5);
        jScrollPane2.setViewportView(txtAreaSend);

        btnSend.setText("Send");

        lbSendTo.setText("...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelChatView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSend))
                            .addComponent(lbSendTo))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbSendTo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelChatView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))))
                .addGap(0, 21, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Private", jPanel1);

        jButton1.setText("Create");

        jTextField1.setText("jTextField1");

        jButton2.setText("Find Room");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(325, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Group", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 369, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("ALL", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblOnlineUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOnlineUsersMouseClicked
        JTable source = (JTable) evt.getSource();
        int row = source.rowAtPoint(evt.getPoint());
        int column = source.columnAtPoint(evt.getPoint());
        String username = source.getModel().getValueAt(row, column).toString();
        updateChatViewPanel(username);
    }//GEN-LAST:event_tblOnlineUsersMouseClicked

    private void updateChatViewPanel(String username) {
        panelChatView.removeAll();

        JScrollPane jScrollPane = this.listOnlineUsers.get(username);
        panelChatView.add(jScrollPane);
        jScrollPane.setSize(panelChatView.getWidth(), panelChatView.getHeight());
        jScrollPane.setVisible(true);

        panelChatView.revalidate();

        lbSendTo.setText(username);

//        appendToTextPane((JTextPane) jScrollPane.getViewport().getComponents()[0],
//                "<div style='background-color:white; color:red'>" + "hi" + "</div>");
    }

    private void appendToTextPane(JTextPane jTextPane, String message) {
        HTMLDocument doc = (HTMLDocument) jTextPane.getDocument();
        HTMLEditorKit editorKit = (HTMLEditorKit) jTextPane.getEditorKit();

        try {
            editorKit.insertHTML(doc, doc.getLength(), message, 0, 0, null);
            jTextPane.setCaretPosition(doc.getLength());
        } catch (BadLocationException ex) {
            Logger.getLogger(Chat.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Chat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void updateStatus(String usernameFrom, int status) {
        if (!this.listOnlineUsers.containsKey(usernameFrom) && status == 1) {
            JTextPane jTextPane = new JTextPane();
            JScrollPane jScrollPane = new JScrollPane(jTextPane);
            jScrollPane.setName(usernameFrom);
            jTextPane.setEditable(false);
            jTextPane.setContentType("text/html");
            jTextPane.setBackground(Color.WHITE);
            jTextPane.setForeground(Color.WHITE);
            jTextPane.setFont(new Font("Courier New", Font.PLAIN, 18));
            updateStatusTable(usernameFrom, status);
            this.listOnlineUsers.put(usernameFrom, jScrollPane);
        } else if (this.listOnlineUsers.containsKey(usernameFrom) && status == 0) {
            updateStatusTable(usernameFrom, status);
            updateReceiveMessage(usernameFrom, "bye im offline now");
            this.listOnlineUsers.remove(usernameFrom);
        }
    }

    private void updateStatusTable(String usernameFrom, int status) {
        DefaultTableModel model = (DefaultTableModel) tblOnlineUsers.getModel();
        if (status == 1) {
            model.addRow(new Object[]{usernameFrom});
        } else if (status == 0) {
            for (int i = 0; i < model.getRowCount(); i++) {
                if (model.getValueAt(i, 0).toString().equals(usernameFrom)) {
                    model.removeRow(i);
                    System.out.println("remove: " + usernameFrom);
                    break;
                }
            }
        }
    }

    public void updateReceiveMessage(String usernameFrom, String message) {
        if (this.listOnlineUsers.containsKey(usernameFrom)) {
            appendToTextPane((JTextPane) this.listOnlineUsers.get(usernameFrom).getViewport().getComponents()[0],
                    "<div style='width: 40%; background-color: white; color: black; margin-top: 4px; float: left'>"
                    + usernameFrom + ": "
                    + message + "</div>");
        }
    }

    public void updateSendMessage(String usernameTo, String message) {
        if (this.listOnlineUsers.containsKey(usernameTo)) {
            appendToTextPane((JTextPane) this.listOnlineUsers.get(usernameTo).getViewport().getComponents()[0],
                    "<div style='width: 40%; background-color: white; color: black; margin-top: 4px; float: right'>"
                    + "me: " + message + "</div>");
        }
    }

    //group
//    private void updateChatRoomViewPanel(String roomname) {
//        chatRoomView.removeAll();
//
//        JScrollPane jScrollPane = this.listRooms.get(roomname);
//        chatRoomView.add(jScrollPane);
//        jScrollPane.setSize(chatRoomView.getWidth(), chatRoomView.getHeight());
//        jScrollPane.setVisible(true);
//
//        chatRoomView.revalidate();
//    }
//    public void updateRoomStatus(String roomname) {
//        System.out.println("updating room status...");
//        if ((!this.listRooms.containsKey(roomname))) {
//            JTextPane jTextPane = new JTextPane();
//            JScrollPane jScrollPane = new JScrollPane(jTextPane);
//            jScrollPane.setName(roomname);
//            jTextPane.setEditable(false);
//            jTextPane.setContentType("text/html");
//            jTextPane.setBackground(Color.BLACK);
//            jTextPane.setForeground(Color.WHITE);
//            jTextPane.setFont(new Font("Courier New", Font.PLAIN, 18));
//            appendToTextPane(jTextPane, "<div class='clear' style='background-color:white; color:red; position: fixed'>" + roomname + "</div>");
//            udateStatusRoomTable(roomname);
//            this.listRooms.put(roomname, jScrollPane);
//        }
//    }
//    private void udateStatusRoomTable(String roomname) {
//        DefaultTableModel model = (DefaultTableModel) tblRoom.getModel();
//        model.addRow(new Object[]{roomname});
//    }
    public void updateReceiveRoomMessage(String usernameFrom, String roomname, String message) {
        System.out.println("432: updatereceive");
        if (this.listRooms.containsKey(roomname)) {
            appendToTextPane((JTextPane) this.listRooms.get(roomname).getViewport().getComponents()[0],
                    "<div style='width: 40%; background-color: blue; margin-top: 4px; float: left'>" + "    "
                    + "From: " + usernameFrom + "<br>" + message
                    + "<br>" + LocalDateTime.now().getHour() + ":" + LocalDateTime.now().getMinute() + "</div>");
        }
    }

    public void updateSendRoomMessage(String roomname, String message) {
        if (this.listRooms.containsKey(roomname)) {
            appendToTextPane((JTextPane) this.listRooms.get(roomname).getViewport().getComponents()[0],
                    "<div style='width: 40%; background-color: blue; margin-top: 4px; float: right'>" + "    " + "<br>" + message
                    + "<br>" + LocalDateTime.now().getHour() + ":" + LocalDateTime.now().getMinute() + "</div>");
        }
    }

    public void addCloseListener(WindowAdapter windowAdapter) {
        this.addWindowListener(windowAdapter);
    }

    public void show(String content) {
        JOptionPane.showMessageDialog(null, content);
    }

    public int confirm(String confirmContent) {
        int res = JOptionPane.showConfirmDialog(this, confirmContent);
        return res;
    }

    public String getLbSendTo() {
        return lbSendTo.getText();
    }

    public String getTxtAreaSend() {
        return txtAreaSend.getText();
    }

    public void clearTxtAreaSend() {
        txtAreaSend.setText("");
    }

    public void addButtonListener(ActionListener actionListener) {
        btnSend.addActionListener(actionListener);
//        btnSendRoom.addActionListener(actionListener);
//        btnCreate.addActionListener(actionListener);
//        btnSendRoom.addActionListener(actionListener);
//        btnJoin.addActionListener(actionListener);
//        btnFind.addActionListener(actionListener);

    }

    //group
//    public String getRoomname() {
//        return txtRoomname.getText();
//    }
//
//    public String getRoomnameTo() {
//        return sendRoomLabel.getText();
//    }
//
//    public String getSendRoomText() {
//        return sendRoomTextArea.getText();
//    }
//
//    public void clearSendRoomTextArea() {
//        sendRoomTextArea.setText("");
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSend;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbSendTo;
    private javax.swing.JPanel panelChatView;
    private javax.swing.JTable tblOnlineUsers;
    private javax.swing.JTextArea txtAreaSend;
    // End of variables declaration//GEN-END:variables
}
